### ISSUE TITLE
resolver_external check treats private subnets as external

### ISSUE THREAD

**Issue by doc-sheet** [dvershinin/gixy#5]
Hi!
`resolver_external` plugin reacts to 10.0.0.1 (well, anything other then localhost).

I guess private ipv4/ipv6 subnets should be excluded too.

**Comment by AgentOak** [comment]
Same for the loopback net 127.0.0.0/8, e.g. `127.0.0.53` which is the default address systemd-resolved binds to.

**Comment by dvershinin** [comment]
Fixed in v0.1.23.
