### ISSUE TITLE
Issue with the includes processing

### ISSUE THREAD

**Issue by aseques** [dvershinin/gixy#6]
My nginx configuration is triggered by the "Allow without deny" plugin (see https://github.com/yandex/gixy/commit/3772b6e810beb079f9e7b3dc5774c52ec2d49160), I am including files with the host to allow, and then a deny line to deny the rest.
It seems that gixy-ng is not detecting this case because the Pseudo config doesn't show the deny line

```
server {
    listen 443;
    server_name app.example.com;

    location / {
        alias /var/www/html/;
        include ../test.conf;
        deny all;
    }
}

```

The file test.conf being:
`allow 1.1.1.1;`

The message being 

```

>> Problem: [allow_without_deny] Found allow directive(s) without deny in the same context.
Description: The "allow" directives should be typically accompanied by "deny all;" directive
Additional info: https://github.com/dvershinin/gixy/blob/master/docs/en/plugins/allow_without_deny.md
Reason: You probably want "deny all;" after all the "allow" directives
Pseudo config:

server {
        server_name app.example.com;

        location / {

                include /etc/nginx/sites-available/../test.conf;
                        allow 1.1.1.1;
        }
}

```

Thanks a lot for your improvements to gixy, it's really a neat tool

**Comment by dvershinin** [comment]
@aseques It has now been fixed in v0.2.1
